
CREATE OR REPLACE PROCEDURE CC_initialize(OUT TOT_XOM DECFLOAT,OUT TOT_AAL DECFLOAT,OUT STOT_XOM DECFLOAT,OUT STOT_AAL DECFLOAT,OUT TOT DECFLOAT, OUT N INT)
LANGUAGE SQL
CONTAINS SQL
BEGIN
  SET TOT_XOM = 0;
  SET TOT_AAL = 0;
  SET STOT_XOM = 0;
  SET STOT_AAL = 0;
  SET TOT = 0;
  SET N = 0;
END @

CREATE OR REPLACE PROCEDURE CC_accumulate(IN XOM_CLOSE DECFLOAT,IN AAL_CLOSE DECFLOAT, INOUT TOT_XOM DECFLOAT,INOUT TOT_AAL DECFLOAT, INOUT STOT_XOM DECFLOAT,INOUT STOT_AAL DECFLOAT,INOUT TOT DECFLOAT, INOUT N INT)
LANGUAGE SQL
CONTAINS SQL
BEGIN
  SET TOT_XOM = TOT_XOM+XOM_CLOSE;
  SET TOT_AAL = TOT_AAL+AAL_CLOSE;
  SET STOT_XOM = STOT_XOM+ POWER(XOM_CLOSE,2);
  SET STOT_AAL = STOT_AAL+POWER(AAL_CLOSE,2);
  SET TOT = TOT+(XOM_CLOSE*AAL_CLOSE);
  SET N = N+1;
END @

CREATE OR REPLACE PROCEDURE CC_merge(IN TOT_XOM DECFLOAT,IN TOT_AAL DECFLOAT,
IN STOT_XOM DECFLOAT,IN STOT_AAL DECFLOAT,IN TOT DECFLOAT, IN N INT, 
INOUT MTOT_XOM DECFLOAT,INOUT MTOT_AAL DECFLOAT, INOUT MSTOT_XOM DECFLOAT,
INOUT MSTOT_AAL DECFLOAT,INOUT MTOT DECFLOAT, INOUT MN INT)
LANGUAGE SQL
CONTAINS SQL
BEGIN
  SET MTOT_XOM = MTOT_XOM+TOT_XOM;
  SET MTOT_AAL = MTOT_AAL+TOT_AAL;
  SET MSTOT_XOM = MSTOT_XOM+STOT_XOM;
  SET MSTOT_AAL = MSTOT_AAL+STOT_AAL;
  SET MTOT = MTOT+TOT;
  SET MN = MN+N;
END @

CREATE OR REPLACE FUNCTION CC_finalize(TOT_XOM DECFLOAT,TOT_AAL DECFLOAT,STOT_XOM DECFLOAT, STOT_AAL DECFLOAT, TOT DECFLOAT, N INT)
LANGUAGE SQL
CONTAINS SQL
RETURNS DECFLOAT
BEGIN
  RETURN ((N*(TOT))-(TOT_XOM*TOT_AAL))/SQRT(((N*STOT_XOM)-(TOT_XOM*TOT_XOM))*((N*STOT_AAL)-(TOT_AAL*TOT_AAL)));	     
END @

CREATE OR REPLACE FUNCTION PearsonCC(DECFLOAT,DECFLOAT)
RETURNS DECFLOAT(34)
AGGREGATE WITH (TOT_XOM DECFLOAT,TOT_AAL DECFLOAT,STOT_XOM DECFLOAT, STOT_AAL DECFLOAT, TOT DECFLOAT, N INT)
USING
INITIALIZE PROCEDURE CC_initialize
ACCUMULATE PROCEDURE CC_accumulate
MERGE PROCEDURE CC_merge
FINALIZE FUNCTION CC_finalize
@


SELECT CAST (CC(x.CLOSE, a.CLOSE) AS DECIMAL(4,3)) AS PEARSON_CORRELATION_COEFFICIENT
FROM CSE532.Stock x, CSE532.Stock a 
WHERE x.DATE =a.DATE AND x.STOCKNAME <> a.STOCKNAME AND x.STOCKNAME ='XOM'; @