
SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;

SELECT 
t.FACILITY_NAME , t.ST ,t.CARCINOGEN, 
DB2GSE.ST_ASTEXT(t.GEOLOCATION),
cast(DB2GSE.ST_Distance(t.GEOLOCATION , DB2GSE.ST_POINT(-73.116371, 40.913780, 1), 'STATUTE MILE') AS DECIMAL(10, 4)) as distance
FROM
CSE532.TRIFACILITY AS t 
WHERE 
t.CARCINOGEN  = 'YES'
AND
DB2GSE.ST_Contains(DB2GSE.ST_Buffer(DB2GSE.ST_POINT(-73.116371, 40.913780, 1), 10, 'STATUTE MILE'), t.GEOLOCATION) = 1
ORDER BY distance
LIMIT 1
;


SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;