SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;

WITH NEIGHBOUR (shape,zipcode)
AS (SELECT z1.SHAPE, z1.ZIPCODE 
FROM CSE532.ZCTA AS z1
WHERE db2gse.ST_Intersects(z1.SHAPE  , 
(SELECT z2.shape FROM CSE532.ZCTA AS z2 WHERE z2.ZIPCODE ='11735' )) = TRUE)


--SELECT * FROM NEIGHBOUR;

SELECT DISTINCT (t.FACILITY_NAME),n.zipcode
FROM cse532.TRIFACILITY AS t, NEIGHBOUR AS n
WHERE  db2gse.ST_Within(t.GEOLOCATION ,n.SHAPE)
 
;


SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;




--SELECT z.SHAPE  
--FROM CSE532.ZCTA AS z
--WHERE db2gse.ST_Intersects(z.SHAPE  , (SELECT z2.shape FROM CSE532.ZCTA AS z2 WHERE z2.ZIPCODE ='11735' )) = TRUE 
--;